### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [tabler/tabler#1291]
I'm facing the following issue while running the application.

```
$ npm run start-plugins

> @tabler/core@1.0.0-beta12 start-plugins
> gulp start --with-plugins

ReferenceError: primordials is not defined
    at fs.js:47:5
    at req_ (/path-to-code/tabler/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/path-to-code/tabler/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/path-to-code/tabler/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

**Comment by UnnikrishnanBhargavakurup** [comment]
please ignore fixed using the followeing method 

https://stackoverflow.com/questions/63711192/i-get-the-error-fs-js36-primordials-referenceerror-primordials-is-not
