### ISSUE TITLE
Tabler with Laravel 9 + Vite

### ISSUE THREAD

**Issue by yjungles** [tabler/tabler#1394]
Has anyone found a solution for using Tabler with Laravel 9+Vite?

For now, I'm just importing the CDN directly in the layout, overriding ::root variables directly in the css, but I believe this is not a good solution at all

**Comment by tinyoverflow** [comment]
You can simply install the Tabler Core package and then include it inside the CSS and JS file.

```
npm install --dev @tabler/core 
```

```js
// resources/js/app.js
import '@tabler/core';
```

```scss
// resources/css/app.css
@import "@tabler/core";
```

Then simply embed Vite in your preferred way (eg. using `@vite(...)` in Blade) and start your Vite server with `npm run dev`.

**Comment by corean** [comment]
```
// resources/js/app.js
import '@tabler/core/src/js/tabler.js';

// resources/sass/app.scss
@import '@tabler/core/src/scss/tabler';
```

**Comment by Dibbyo456** [comment]
````
 harry@Harrys-MacBook-Air  ~/c-market  pnpm build

> @ build /Users/harry/c-market
> vite build

vite v4.1.1 building for production...
✓ 17 modules transformed.
transforming (18) node_modules/.pnpm/lodash.isequal@4.5.0/node_modules/lodash.isequal/index.js12:50:38 PM [vite-plugin-svelte] dom compile done.
package                 files     time     avg
@inertiajs/svelte           4   45.2ms  11.3ms
$unknown                    1   13.7ms  13.7ms
[vite:css] [sass] Can't find stylesheet to import.
  ╷
1 │ @import "../node_modules/bootstrap/scss/bootstrap";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/.pnpm/@tabler+core@1.0.0-beta17/node_modules/@tabler/core/src/scss/_config.scss 1:9  @import
  node_modules/.pnpm/@tabler+core@1.0.0-beta17/node_modules/@tabler/core/src/scss/_core.scss 1:9    @import
  node_modules/.pnpm/@tabler+core@1.0.0-beta17/node_modules/@tabler/core/src/scss/tabler.scss 1:9   @import
  resources/scss/app.scss 5:9                                                                       root stylesheet
file: /Users/harry/c-market/resources/scss/app.scss
Error: Can't find stylesheet to import.
  ╷
1 │ @import "../node_modules/bootstrap/scss/bootstrap";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/.pnpm/@tabler+core@1.0.0-beta17/node_modules/@tabler/core/src/scss/_config.scss 1:9  @import
  node_modules/.pnpm/@tabler+core@1.0.0-beta17/node_modules/@tabler/core/src/scss/_core.scss 1:9    @import
  node_modules/.pnpm/@tabler+core@1.0.0-beta17/node_modules/@tabler/core/src/scss/tabler.scss 1:9   @import
  resources/scss/app.scss 5:9                                                                       root stylesheet
error during build:
Error: Can't find stylesheet to import.
  ╷
1 │ @import "../node_modules/bootstrap/scss/bootstrap";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/.pnpm/@tabler+core@1.0.0-beta17/node_modules/@tabler/core/src/scss/_config.scss 1:9  @import
  node_modules/.pnpm/@tabler+core@1.0.0-beta17/node_modules/@tabler/core/src/scss/_core.scss 1:9    @import
  node_modules/.pnpm/@tabler+core@1.0.0-beta17/node_modules/@tabler/core/src/scss/tabler.scss 1:9   @import
  resources/scss/app.scss 5:9                                                                       root stylesheet
    at Object.wrapException (/Users/harry/c-market/node_modules/.pnpm/sass@1.58.1/node_modules/sass/sass.dart.js:1250:17)
    at /Users/harry/c-market/node_modules/.pnpm/sass@1.58.1/node_modules/sass/sass.dart.js:70914:25
    at _wrapJsFunctionForAsync_closure.$protected (/Users/harry/c-market/node_modules/.pnpm/sass@1.58.1/node_modules/sass/sass.dart.js:3841:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/Users/harry/c-market/node_modules/.pnpm/sass@1.58.1/node_modules/sass/sass.dart.js:28638:12)
    at _awaitOnObject_closure.call$1 (/Users/harry/c-market/node_modules/.pnpm/sass@1.58.1/node_modules/sass/sass.dart.js:28626:32)
    at Object._rootRunUnary (/Users/harry/c-market/node_modules/.pnpm/sass@1.58.1/node_modules/sass/sass.dart.js:4216:18)
    at StaticClosure.<anonymous> (/Users/harry/c-market/node_modules/.pnpm/sass@1.58.1/node_modules/sass/sass.dart.js:99626:16)
    at _CustomZone.runUnary$2$2 (/Users/harry/c-market/node_modules/.pnpm/sass@1.58.1/node_modules/sass/sass.dart.js:30035:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (/Users/harry/c-market/node_modules/.pnpm/sass@1.58.1/node_modules/sass/sass.dart.js:29107:51)
    at Object._Future__propagateToListeners (/Users/harry/c-market/node_modules/.pnpm/sass@1.58.1/node_modules/sass/sass.dart.js:4012:93)
 ELIFECYCLE  Command failed with exit code 1.
 ✘ harry@Harrys-MacBook-Air  ~/c-market  
````

**Comment by tinyoverflow** [comment]
@Dibbyo456 Sorry, but my magic crystal ball is currently broken.

**Comment by Dibbyo456** [comment]
I've created https://github.com/Dibbyo456/tabler-bug-report repo replicating the error.
Follow the read me for instruction.

**Comment by tinyoverflow** [comment]
@Dibbyo456 please create a new issue for this. I've investigated this and your problem is not related to this issue.

You might want to reference #1384, as this is kinda related to that, which is the PR that broke imports in some cases by hardcoding paths instead of letting the compiler do that.

Until this gets resolved, you might have some luck by aliasing that path in your `vite.config.js`:
```
    resolve: {
        alias: {
            "~bootstrap": "bootstrap",
            "../../node_modules/bootstrap": "bootstrap",
        },
    },
```

**Comment by SyntaxJoker** [comment]
We will be fixing import issues in https://github.com/tabler/tabler/pull/1477
as for using Tabler with Laravel 9+Vite, you can `npm install @tabler/core` and import js,scss from it as others mentioned
