### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by mantrakp2004** [tabler/tabler#1465]
Followed the instructions, made a droplet on digital ocean, cloned the git repo installed packages, npm, ruby etc all of it but when i type npm run start it gives an error

`/root/tabler/tabler/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/tabler/tabler/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)`

**Comment by mholt** [comment]
I have absolutely no experience with this stuff, but my guess is an old version of Node or whatever is parsing the JS, since `?.` is a relatively new operator.
