### ISSUE TITLE
[BUG] Docker image

### ISSUE THREAD

**Issue by leonardoborlot** [tabler/tabler#1512]
**Describe the bug**

When you try to start a container, recive this log:

[02:56:34] Starting 'js'...
[02:56:35] 'js' errored after 432 ms
[02:56:35] Error: Could not resolve entry module (./src/js/tabler.js).
    at error (/app/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.loadEntryModule (/app/node_modules/rollup/dist/shared/rollup.js:22306:20)
    at async Promise.all (index 0)
[02:56:35] 'start' errored after 7.27 s

**Device**

 - Docker

**To reproduce**

1. Download project from git
2. Compile image from Dockerfile in project
3. docker runcontainer with this image
4. See error in log

**Screenshots**

![image](https://user-images.githubusercontent.com/20361821/227089500-871e1ff2-3272-48b7-b9a5-d45551488f17.png)

**Comment by leonardoborlot** [comment]
Sorry, I mistake, forget the src folder....
