### ISSUE TITLE
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'

### ISSUE THREAD

**Issue by hamada147** [tabler/tabler#155]
I'm using Ruby v2.6.14.1 provided by this command gem -v

I've followed all the instruction provided in the documentation but I'm unable to figure this one.
First I faced some issues because I had two version of a couple of ruby libraries, so I uninstalled them then installed the specific version required. 
After fixing this issue I got this one which I'm kind of lost and I don't really get why it is unable to preform the command.
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'

I tried to uninstall it using this gem uninstall eventmachine
then reinstall it using this bundle install
but no luck

the following is the complete log file

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Moussa\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'serve' ]
2 info using npm@6.1.0
3 info using node@v8.9.0
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle tabler-ui@0.0.32~preserve: tabler-ui@0.0.32
6 info lifecycle tabler-ui@0.0.32~serve: tabler-ui@0.0.32
7 verbose lifecycle tabler-ui@0.0.32~serve: unsafe-perm in lifecycle true
8 verbose lifecycle tabler-ui@0.0.32~serve: PATH: C:\Users\Moussa\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\wamp64\www\tabler-master\node_modules\.bin;C:\Program Files\Python36\Scripts\;C:\Program Files\Python36\;C:\Program Files (x86)\Python36-32\Scripts\;C:\Program Files (x86)\Python36-32\;c:\programdata\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\skype\phone\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files\dotnet\;c:\program files (x86)\microsoft sql server\100\tools\binn\;c:\program files\microsoft sql server\100\tools\binn\;c:\program files\microsoft sql server\100\dts\binn\;c:\program files (x86)\microsoft sql server\100\tools\binn\vsshell\common7\ide\;c:\program files (x86)\microsoft visual studio 9.0\common7\ide\privateassemblies\;c:\program files (x86)\microsoft sql server\100\dts\binn\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Ruby24-x64\bin;C:\Users\Moussa\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bi;;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Users\Moussa\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Python27;C:\Python27\Scripts;C:\Users\Moussa\AppData\Roaming\npm;C:\Users\Moussa\AppData\Local\atom\bin;C:\Users\Moussa\AppData\Local\Microsoft\WindowsApps
9 verbose lifecycle tabler-ui@0.0.32~serve: CWD: C:\wamp64\www\tabler-master
10 silly lifecycle tabler-ui@0.0.32~serve: Args: [ '/d /s /c',
10 silly lifecycle   'gulp build && npm-run-all --parallel gulp-watch jekyll-serve' ]
11 silly lifecycle tabler-ui@0.0.32~serve: Returned: code: 1  signal: null
12 info lifecycle tabler-ui@0.0.32~serve: Failed to exec serve script
13 verbose stack Error: tabler-ui@0.0.32 serve: `gulp build && npm-run-all --parallel gulp-watch jekyll-serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Moussa\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Moussa\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid tabler-ui@0.0.32
15 verbose cwd C:\wamp64\www\tabler-master
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Moussa\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
18 verbose node v8.9.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error tabler-ui@0.0.32 serve: `gulp build && npm-run-all --parallel gulp-watch jekyll-serve`
22 error Exit status 1
23 error Failed at the tabler-ui@0.0.32 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by LiPan1988** [comment]
> I was finally able to make it work by doing the following
> 
> go to this folder C:\Ruby24-x64\lib\ruby\gems\2.4.0\gems\eventmachine-1.2.5-x64-mingw32\lib
> open this file eventmachine.rb
> write this
> require 'em/pure_ruby'
> in the first line of code in the file
> this will make it work with no issues.
> 
> Perfect - work for me.

this also work for me. thank you so much! appreciate you!!

**Comment by treanaslocum** [comment]
Thanks I was struggling with this.

**Comment by carlosjcuevasm** [comment]
Following Jekyll guide for installation on Windows, right now with Ruby 2.7. The steps here do still work. I'm able to --livereload. Do place the require on the first line of the file, not alongside the others requires, as this did not work for me.

**Comment by samhiatt** [comment]
hamada147's solution resolved the issue for me. I had trouble finding the correct file to patch, so I wrote an ugly batch script to find and patch it. 
Check it out here: https://gist.github.com/samhiatt/5fea77154d17566d6addf6d2c4505aeb

**Comment by majedooona** [comment]
TERMUX 👇

1-  cd ..
2-  cd usr/lib/ruby/gems/2.7.0/gems/cd eventmachine-1.2.7/lib
3-  nano eventmachine.rb
قم بكتابة هذا بالسطر اول بالبدايه
require 'em/pure_ruby'

أإأذأإأ مادخلت للمكان المطلوب عدل الارقام على حسب التحديث الموجود عندك 
وذلك عبر الانتقال على امر واحد مثل
cd usr
ls
cd lib
ls
ونظر ماهو موجود عندك وادخله 
واكمل الباقي نفس الطريقه
