### ISSUE TITLE
Local setup not working as per the documentation. 

### ISSUE THREAD

**Issue by pereiraryan** [tabler/tabler#160]
I am trying to set up a local instance of this project. While running the command to start the dev server i get an error. 
My environment details are :  `npm -v : 6.1.0`  `node -v : v8.11.3`  

the error thrown on the terminal is  

`> tabler-ui@0.0.32 serve /var/www/html/gatsby/tabler
> gulp build && npm-run-all --parallel gulp-watch jekyll-serve

assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/var/www/html/gatsby/tabler/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/var/www/html/gatsby/tabler/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/var/www/html/gatsby/tabler/gulpfile.js:42:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tabler-ui@0.0.32 serve: `gulp build && npm-run-all --parallel gulp-watch jekyll-serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tabler-ui@0.0.32 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by ItStark** [comment]
try `gem install jekyll bundler` and restart prompt as administrator, worked for me

**Comment by ItStark** [comment]
Try  `gem install jekyll` bundler and restart prompt as administrator then `npm run serve`  worked for me.
If this not works too, uninstall eventmachine `gem uninstall eventmachine` ,
finally install it again `gem install eventmachine --platform ruby` and `npm run serve`, it most probably will work.

**Comment by neloaguila** [comment]
I had the same error and did what @ItStark suggested. Still not working. Same error still arise.

**Comment by mwilliams1188** [comment]
Bump this. Tried a lot of different solutions now and nothing. Any updates?
