### ISSUE TITLE
[BUG] Docker Build Fails

### ISSUE THREAD

**Issue by kanade0404** [tabler/tabler#1627]
**Describe the bug**

The Docker build fails when following the provided build instructions in the README.

**Device**

- OS: macOS 12.6.3 (Build 21G419)
- Docker version:
  - Client:
    - Cloud integration: v1.0.31
    - Version: 20.10.23
    - API version: 1.41
    - Go version: go1.18.10
    - Git commit: 7155243
    - Built: Thu Jan 19 17:35:19 2023
    - OS/Arch: darwin/arm64
    - Context: default
    - Experimental: true
  - Server: Docker Desktop 4.17.0 (99724)
    - Engine:
      - Version: 20.10.23
      - API version: 1.41 (minimum version 1.12)
      - Go version: go1.18.10
      - Git commit: 6051f14
      - Built: Thu Jan 19 17:31:28 2023
      - OS/Arch: linux/arm64
      - Experimental: false
    - containerd:
      - Version: 1.6.18
      - GitCommit: 2456e983eb9e37e47538f59ea18f2043c9a73640
    - runc:
      - Version: 1.1.4
      - GitCommit: v1.1.4-0-g5fd4c4d
    - docker-init:
      - Version: 0.19.0
      - GitCommit: de40ad0

**To reproduce**

1. Clone the repository.
2. Execute the following command:
   ```shell
   docker run -p 3000:3000 -p 3001:3001 -v $(pwd)/src:/app/src -v $(pwd)/_config.yml:/app/_config.yml tabler
   ```
3. Observe the error during the build process.

I tried to clone and build the project, but I encountered several issues.

- The Dockerfile is outdated:
  - It doesn't install pnpm.
  - The lock file being copied is still `package-lock.json`.
  - The `ENTRYPOINT` command `pnpm run start-plugins` doesn't exist in the current npm scripts.

- `_config_prod.yml` needs to be created and mounted as a volume; otherwise, it causes an error in the gulpfile.

```shell
docker run -p 3000:3000 -p 3001:3001 -v $(pwd)/src:/app/src -v $(pwd)/_config.yml:/app/_config.yml tabler
 WARN  Unsupported engine: wanted: {"node":">=18"} (current: {"node":"v16.20.0","pnpm":"8.6.2"})

> @tabler/core@1.0.0-beta19 start /app
> gulp start

[15:28:10] Using gulpfile /app/gulpfile.js
[15:28:10] Starting 'start'...
[15:28:10] Starting 'clean'...
[15:28:10] Starting 'clean-dirs'...
[15:28:10] Finished 'clean-dirs' after 9.86 ms
[15:28:10] Starting 'clean-jekyll'...
Configuration file: /app/_config.yml
           Cleaner: Nothing to do for tmp.
           Cleaner: Nothing to do for src/pages/.jekyll-metadata.
           Cleaner: Nothing to do for src/pages/.jekyll-cache.
           Cleaner: Nothing to do for .sass-cache.
[15:28:11] Finished 'clean-jekyll' after 343 ms
[15:28:11] Finished 'clean' after 354 ms
[15:28:11] Starting 'sass'...
[15:28:11] gulp-debug: src/scss/demo.scss
[15:28:11] gulp-debug: src/scss/tabler.scss
[15:28:11] gulp-debug: 2

 items
[15:28:17] Finished 'sass' after 6.11 s
[15:28:17] Starting 'js'...
[15:28:18] Finished 'js' after 1.48 s
[15:28:18] Starting 'js-demo'...
[15:28:18] Starting 'js-demo-theme'...
[15:28:18] Finished 'js-demo' after 58 ms
[15:28:18] Finished 'js-demo-theme' after 58 ms
[15:28:18] Starting 'mjs'...
[15:28:19] Finished 'mjs' after 998 ms
[15:28:19] Starting 'build-jekyll'...
Configuration file: /app/_config.yml
             Fatal: The configuration file '/app/_config_prod.yml' could not be found.
bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
LoadError: The Configuration file '/app/_config_prod.yml' could not be found.
  /usr/local/bundle/gems/jekyll-4.3.1/lib/jekyll/configuration.rb:181:in `rescue in read_config_file'
  /usr/local/bundle/gems/jekyll-4.3.1/lib/jekyll/configuration.rb:165:in `read_config_file'
  /usr/local/bundle/gems/jekyll-4.3.1/lib/jekyll/configuration.rb:198:in `block in read_config_files'
  /usr/local/bundle/gems/jekyll-4.3.1/lib/jekyll/configuration.rb:195:in `each'
  /usr/local/bundle/gems/jekyll-4.3.1/lib/jekyll/configuration.rb:195:in `read_config_files'
  /usr/local/bundle/gems/jekyll-4.3.1/lib/jekyll.rb:118:in `configuration'
  /usr/local/bundle/gems/jekyll-4.3.1/lib/jekyll/command.rb:44:in `configuration_from_options'
  /usr/local/bundle/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:29:in `process'
  /usr/local/bundle/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
  /usr/local/bundle/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `each'
  /usr/local/bundle/gems/jekyll-4.3.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
  /usr/local/bundle/gems/jekyll-4.3.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
  /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
  /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
  /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
  /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
  /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
  /usr/local/bundle/gems/jekyll-4.3.1/exe/jekyll:15

:in `<top (required)>'
  /usr/local/bundle/bin/jekyll:23:in `load'
  /usr/local/bundle/bin/jekyll:23:in `<top (required)>'
[15:28:20] 'build-jekyll' errored after 309 ms
[15:28:20] Error: exited with error code: 1
    at ChildProcess.onexit (/app/node_modules/.pnpm/end-of-stream@1.4.4/node_modules/end-of-stream/index.js:40:36)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:552:15)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)
[15:28:20] 'start' errored after 9.31 s
 ELIFECYCLE  Command failed with exit code 1.
```

I will submit a pull request at a later date.
**Screenshots**

If applicable, add screenshots to help explain the problem.

**Comment by olariuromeo** [comment]
any update to this error?

**Comment by mattsmithdev** [comment]
I was able to get it working with the following Dockerfile...
```
FROM ruby:2.7-alpine

WORKDIR /app
ADD _config.yml /app/
ADD _config_prod.yml /app/
ADD Gemfile /app/
ADD Gemfile.lock /app/
ADD package.json /app/
ADD pnpm-lock.yaml /app/
ADD gulpfile.js /app/

RUN apk add --virtual build-dependencies build-base
RUN apk add npm --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community/
RUN npm i -g pnpm
RUN pnpm install
RUN bundle config --global silence_root_warning 1 && bundler install --verbose

# website
EXPOSE 3000
# website management (browser auto reload)
EXPOSE 3001
# run tabler
ENTRYPOINT [ "pnpm", "run", "start-plugins" ]
```
Then run...
`docker build -t tabler .`
and finally...
`docker run -p 3000:3000 -p 3001:3001 -v $(pwd)/src:/app/src tabler`

**Comment by rjd22** [comment]
Should be fixed now.
