### ISSUE TITLE
[BUG] Unable to run Docker Image

### ISSUE THREAD

**Issue by janstadt** [tabler/tabler#1955]
### Browser

Chrome latest

### OS

Mac OS Sonoma 14.4.1

### Screen size

1920x1080

### Describe the bug

Following the documentation to run tabler in a container i get the following errors:

```
> @tabler/core@1.0.0-beta21 start-plugins /app
> gulp start --with-plugins

[20:20:55] Using gulpfile /app/gulpfile.js
[20:20:55] Starting 'start'...
[20:20:55] Starting 'clean'...
[20:20:55] Starting 'clean-dirs'...
[20:20:55] Finished 'clean-dirs' after 13 ms
[20:20:55] Starting 'clean-jekyll'...
bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require': cannot load such file -- google/protobuf_c (LoadError)
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf_native.rb:15:in `rescue in <top (required)>'
	from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf_native.rb:12:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf.rb:57:in `<module:Protobuf>'
	from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf.rb:15:in `<module:Google>'
	from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf.rb:14:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/ext/sass/embedded_sass_pb.rb:5:in `<top (required)>'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded_protocol.rb:6:in `require_relative'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded_protocol.rb:6:in `<module:EmbeddedProtocol>'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded_protocol.rb:5:in `<module:Sass>'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded_protocol.rb:3:in `<top (required)>'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/compiler.rb:11:in `require_relative'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/compiler.rb:11:in `<top (required)>'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded.rb:3:in `require_relative'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded.rb:3:in `<top (required)>'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass-embedded.rb:4:in `require_relative'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass-embedded.rb:4:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:8:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/jekyll-sass-converter-3.0.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/jekyll-4.3.3/lib/jekyll.rb:195:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/jekyll-4.3.3/exe/jekyll:8:in `<top (required)>'
	from /usr/local/bundle/bin/jekyll:25:in `load'
	from /usr/local/bundle/bin/jekyll:25:in `<top (required)>'
	from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:492:in `exec'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/libexec/bundle:37:in `block in <top (required)>'
	from /usr/local/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/libexec/bundle:29:in `<top (required)>'
	from /usr/local/bin/bundle:25:in `load'
	from /usr/local/bin/bundle:25:in `<main>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require': Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/3.2/protobuf_c.so) - /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/3.2/protobuf_c.so (LoadError)
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf_native.rb:13:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf.rb:57:in `<module:Protobuf>'
	from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf.rb:15:in `<module:Google>'
	from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf.rb:14:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/ext/sass/embedded_sass_pb.rb:5:in `<top (required)>'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded_protocol.rb:6:in `require_relative'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded_protocol.rb:6:in `<module:EmbeddedProtocol>'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded_protocol.rb:5:in `<module:Sass>'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded_protocol.rb:3:in `<top (required)>'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/compiler.rb:11:in `require_relative'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/compiler.rb:11:in `<top (required)>'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded.rb:3:in `require_relative'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded.rb:3:in `<top (required)>'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass-embedded.rb:4:in `require_relative'
	from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass-embedded.rb:4:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:8:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/jekyll-sass-converter-3.0.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/jekyll-4.3.3/lib/jekyll.rb:195:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /usr/local/bundle/gems/jekyll-4.3.3/exe/jekyll:8:in `<top (required)>'
	from /usr/local/bundle/bin/jekyll:25:in `load'
	from /usr/local/bundle/bin/jekyll:25:in `<top (required)>'
	from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /usr/local/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:492:in `exec'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /usr/local/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /usr/local/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/libexec/bundle:37:in `block in <top (required)>'
	from /usr/local/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/libexec/bundle:29:in `<top (required)>'
	from /usr/local/bin/bundle:25:in `load'
	from /usr/local/bin/bundle:25:in `<main>'
[20:20:56] 'clean-jekyll' errored after 349 ms
[20:20:56] Error: exited with error code: 1
    at ChildProcess.onexit (/app/node_modules/.pnpm/end-of-stream@1.4.4/node_modules/end-of-stream/index.js:40:36)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess.emit (node:domain:551:15)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)
[20:20:56] 'clean' errored after 365 ms
[20:20:56] 'start' errored after 366 ms
 ELIFECYCLE  Command failed with exit code 1.

```

### How to reproduce

1. clone repo (choose dev branch. tried main as well with same results). 
2. build the container `docker compose build && docker compose up`
3. View error and container doesnt start.

**Comment by janstadt** [comment]
https://stackoverflow.com/questions/68630526/lib64-ld-linux-x86-64-so-2-no-such-file-or-directory-error 
`docker build -t tabler --platform linux/x86_64 .` is the key for apple aarch.
