### ISSUE TITLE
Bundle Install Fails

### ISSUE THREAD

**Issue by immu** [tabler/tabler#1968]
Hey guys, wanted to try the dashboard, ended up with the error, could you please help me resolve 

[pnpm run start-plugins](url)

[21:14:15] Using gulpfile G:\Projects\Tabler\tabler\gulpfile.js
[21:14:15] Starting 'start'...
[21:14:15] Starting 'clean'...
[21:14:15] Starting 'clean-dirs'...
[21:14:15] Finished 'clean-dirs' after 13 ms
[21:14:15] Starting 'clean-jekyll'...
**bundler: command not found: jekyll**
Install missing gem executables with `bundle install`
[21:14:16] 'clean-jekyll' errored after 448 ms
**[21:14:16] Error: exited with error code: 127
    at ChildProcess.onexit (G:\Projects\Tabler\tabler\node_modules\end-of-stream\index.js:40:36)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess.emit (node:domain:551:15)
    at cp.emit (G:\Projects\Tabler\tabler\node_modules\cross-spawn\lib\enoent.js:34:29)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)**
[21:14:16] 'clean' errored after 465 ms
[21:14:16] 'start' errored after 468 ms
 **ELIFECYCLE**  Command failed with exit code 1.

**Comment by kevinpapst** [comment]
Here is how to install Jekyll: https://jekyllrb.com/docs/
