### ISSUE TITLE
Docker Image not working 

### ISSUE THREAD

**Issue by dezihh** [tabler/tabler#1993]
### Browser

none

### OS

Debian 12.4 on aarch64 (Raspi 4)

### Screen size

none

### Describe the bug

Docker build is running as expected.
If your start your fresh biulded container it crashes:
```
> @tabler/core@1.0.0-beta21 start-plugins /app
> gulp start --with-plugins

[10:37:17] Using gulpfile /app/gulpfile.js
[10:37:17] Starting 'start'...
[10:37:17] Starting 'clean'...
[10:37:17] Starting 'clean-dirs'...
[10:37:17] Finished 'clean-dirs' after 72 ms
[10:37:17] Starting 'clean-jekyll'...
bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
<internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- google/protobuf_c (LoadError)
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf_native.rb:15:in `rescue in <top (required)>'
        from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf_native.rb:12:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf.rb:57:in `<module:Protobuf>'
        from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf.rb:15:in `<module:Google>'
        from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf.rb:14:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/ext/sass/embedded_sass_pb.rb:5:in `<top (required)>'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded_protocol.rb:6:in `require_relative'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded_protocol.rb:6:in `<module:EmbeddedProtocol>'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded_protocol.rb:5:in `<module:Sass>'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded_protocol.rb:3:in `<top (required)>'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/compiler.rb:11:in `require_relative'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/compiler.rb:11:in `<top (required)>'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded.rb:3:in `require_relative'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded.rb:3:in `<top (required)>'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass-embedded.rb:4:in `require_relative'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass-embedded.rb:4:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/bundle/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:8:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/bundle/gems/jekyll-sass-converter-3.0.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/bundle/gems/jekyll-4.3.3/lib/jekyll.rb:195:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/bundle/gems/jekyll-4.3.3/exe/jekyll:8:in `<top (required)>'
        from /usr/local/bundle/bin/jekyll:25:in `load'
        from /usr/local/bundle/bin/jekyll:25:in `<top (required)>'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/cli.rb:492:in `exec'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/cli.rb:34:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/cli.rb:28:in `start'
        from /usr/local/bundle/gems/bundler-2.4.19/exe/bundle:37:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/bundle/gems/bundler-2.4.19/exe/bundle:29:in `<top (required)>'
        from /usr/local/bundle/bin/bundle:25:in `load'
        from /usr/local/bundle/bin/bundle:25:in `<main>'
<internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require': Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/3.3/protobuf_c.so) - /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/3.3/protobuf_c.so (LoadError)
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf_native.rb:13:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf.rb:57:in `<module:Protobuf>'
        from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf.rb:15:in `<module:Google>'
        from /usr/local/bundle/gems/google-protobuf-4.26.1-aarch64-linux/lib/google/protobuf.rb:14:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/ext/sass/embedded_sass_pb.rb:5:in `<top (required)>'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded_protocol.rb:6:in `require_relative'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded_protocol.rb:6:in `<module:EmbeddedProtocol>'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded_protocol.rb:5:in `<module:Sass>'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded_protocol.rb:3:in `<top (required)>'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/compiler.rb:11:in `require_relative'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/compiler.rb:11:in `<top (required)>'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded.rb:3:in `require_relative'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass/embedded.rb:3:in `<top (required)>'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass-embedded.rb:4:in `require_relative'
        from /usr/local/bundle/gems/sass-embedded-1.75.0-aarch64-linux-musl/lib/sass-embedded.rb:4:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/bundle/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:8:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/bundle/gems/jekyll-sass-converter-3.0.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/bundle/gems/jekyll-4.3.3/lib/jekyll.rb:195:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /usr/local/bundle/gems/jekyll-4.3.3/exe/jekyll:8:in `<top (required)>'
        from /usr/local/bundle/bin/jekyll:25:in `load'
        from /usr/local/bundle/bin/jekyll:25:in `<top (required)>'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/cli.rb:492:in `exec'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/cli.rb:34:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/cli.rb:28:in `start'
        from /usr/local/bundle/gems/bundler-2.4.19/exe/bundle:37:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.4.19/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/bundle/gems/bundler-2.4.19/exe/bundle:29:in `<top (required)>'
        from /usr/local/bundle/bin/bundle:25:in `load'
        from /usr/local/bundle/bin/bundle:25:in `<main>'
[10:37:19] 'clean-jekyll' errored after 2.12 s
[10:37:19] Error: exited with error code: 1
    at ChildProcess.onexit (/app/node_modules/.pnpm/end-of-stream@1.4.4/node_modules/end-of-stream/index.js:40:36)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess.emit (node:domain:551:15)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)
[10:37:19] 'clean' errored after 2.2 s
[10:37:19] 'start' errored after 2.21 s
```

### How to reproduce

1. Build your own container as described in doc
2. Run ```docker run -d -it --name=tabler -v $(pwd)/src:/app/src  -v $(pwd)/_config.yml:/app/_config.yml  tabler```

**Comment by rjd22** [comment]
Just tested the following command and where able to build the docker image:

`docker build -t tabler .`
`docker run -p 3000:3000 -p 3001:3001 -v $(pwd)/src:/app/src -v $(pwd)/_config.yml:/app/_config.yml tabler`
