### ISSUE TITLE
Can't build locally

### ISSUE THREAD

**Issue by sirbully** [tabler/tabler#223]
I encountered an error after I used the `npm run serve` command.

> gulp build && npm-run-all --parallel gulp-watch jekyll-serve

assert.js:265
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (\tabler\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (\tabler\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (\tabler\gulpfile.js:42:6)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tabler-ui@0.0.32 serve: `gulp build && npm-run-all --parallel gulp-watch jekyll-serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tabler-ui@0.0.32 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by krsyoung** [comment]
@sirbully what version of Gulp are you running?

```
$ gulp -v
[16:17:01] CLI version 1.4.0
```

I just cloned and I'm hitting a different issue but this part does seem to work.

**Comment by Nayananga** [comment]
I also faced the same issue, then I installed gulp  using npm install -g gulp-cli and also jekyll using [https://jekyllrb.com/docs/#instructions](url) but still the same, otherwise i followed exact same instructions in the [https://tabler.io/tabler/docs/index.html](url) any help??
