### ISSUE TITLE
Failed at the tabler-ui@0.0.16 serve script.

### ISSUE THREAD

**Issue by bipon68** [tabler/tabler#30]
Got message. This is probably not a problem with npm. There is likely additional logging output above.

**Comment by beeman** [comment]
Can you paste the complete message? As it states: `There is likely additional logging output above`

**Comment by bipon68** [comment]
> tabler-ui@0.0.16 serve /Users/biponbiswas/test/admin/tabler
> gulp build && npm-run-all --parallel gulp-watch jekyll-serve

Using gulpfile ~/test/admin/tabler/gulpfile.js
Starting 'styles'...
Starting 'styles-plugins'...
Finished 'styles' after 769 ms
Finished 'styles-plugins' after 759 ms
Starting 'build'...
Finished 'build' after 493 μs

> tabler-ui@0.0.16 jekyll-serve /Users/biponbiswas/test/admin/tabler
> jekyll serve --livereload


> tabler-ui@0.0.16 gulp-watch /Users/biponbiswas/test/admin/tabler
> gulp watch

Using gulpfile ~/test/admin/tabler/gulpfile.js
Starting 'styles'...
Starting 'styles-plugins'...
WARN: Unresolved specs during Gem::Specification.reset:
      rb-fsevent (>= 0.9.4, ~> 0.9)
      ffi (< 2, >= 0.5.0)
      rouge (< 4, >= 1.7)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:313:in `check_for_activated_spec!': You have already activated public_suffix 3.0.1, but your Gemfile requires public_suffix 3.0.0. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:31:in `block in setup'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/forwardable.rb:229:in `each'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/forwardable.rb:229:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:26:in `map'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:26:in `setup'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler.rb:107:in `setup'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
	from /usr/local/lib/ruby/gems/2.4.0/gems/jekyll-3.7.3/exe/jekyll:11:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tabler-ui@0.0.16 jekyll-serve: `jekyll serve --livereload`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tabler-ui@0.0.16 jekyll-serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/biponbiswas/.npm/_logs/2018-04-03T17_56_46_581Z-debug.log
ERROR: "jekyll-serve" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tabler-ui@0.0.16 serve: `gulp build && npm-run-all --parallel gulp-watch jekyll-serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tabler-ui@0.0.16 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/biponbiswas/.npm/_logs/2018-04-03T17_56_46_700Z-debug.log

**Comment by beeman** [comment]
It looks like there is something wrong with getting `jekyll` started, which might have something to do with your local ruby setup. 

Did you run this step from the README?

> [Install Ruby](https://www.ruby-lang.org/en/documentation/installation/), install [Bundler](https://bundler.io/) with `gem install bundler`, and finally run `bundle install`. This will install all Ruby dependencies, such as Jekyll and plugins.

**Comment by mrdavidrobison** [comment]
I'm getting a similar error and I followed the setup environment steps 1 thru 3. After I run `npm run serve` 

npm run serve
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.4
npm info lifecycle tabler-ui@0.0.31~preserve: tabler-ui@0.0.31
npm info lifecycle tabler-ui@0.0.31~serve: tabler-ui@0.0.31

> tabler-ui@0.0.31 serve /data
> gulp build && npm-run-all --parallel gulp-watch jekyll-serve

[15:49:02] Using gulpfile /data/gulpfile.js
[15:49:02] Starting 'styles'...
[15:49:02] Starting 'styles-plugins'...
Segmentation fault (core dumped)

npm info lifecycle tabler-ui@0.0.31~serve: Failed to exec serve script
npm ERR! Linux 4.9.0-6-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
npm ERR! node v6.11.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! tabler-ui@0.0.31 serve: `gulp build && npm-run-all --parallel gulp-watch jekyll-serve`
npm ERR! Exit status 139
npm ERR!
npm ERR! Failed at the tabler-ui@0.0.31 serve script 'gulp build && npm-run-all --parallel gulp-watch jekyll-serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tabler-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build && npm-run-all --parallel gulp-watch jekyll-serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tabler-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tabler-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/npm-debug.log
