### ISSUE TITLE
Need older npm version for running Tabler locally 

### ISSUE THREAD

**Issue by RyanPisuena** [tabler/tabler#645]
https://preview.tabler.io/docs/index.html

Instructions for running Tabler indicate running npm run serve

Error message from cmd (Windows 10):
C:\Users\Ryan\Desktop\tabler-master>npm run serve

> tabler-ui@0.0.34 serve C:\Users\Ryan\Desktop\tabler-master
> gulp build && npm-run-all --parallel gulp-watch jekyll-serve

fs.js:35
} = primordials;
    ^

**ReferenceError: primordials is not defined**
    at fs.js:35:5
    at req_ (C:\Users\Ryan\Desktop\tabler-master\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\Ryan\Desktop\tabler-master\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\Ryan\Desktop\tabler-master\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tabler-ui@0.0.34 serve: `gulp build && npm-run-all --parallel gulp-watch jekyll-serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tabler-ui@0.0.34 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ryan\AppData\Roaming\npm-cache\_logs\2020-06-09T14_39_37_145Z-debug.log

**Comment by FreexD** [comment]
@RyanPisuena thanks for heads up. I'll look into that issue and upgrade the instructions if necessary.

**Comment by codecalm** [comment]
@RyanPisuena you use `tabler-ui` which is no longer supported. Use `@tabler/core` instead :)
