### ISSUE TITLE
eventmachine issue while "npm run serve"

### ISSUE THREAD

**Issue by DerekTso** [tabler/tabler#71]
`F:\tabler>jekyll -v
jekyll 3.7.3

F:\tabler>npm run serve

> tabler-ui@0.0.31 serve F:\tabler
> gulp build && npm-run-all --parallel gulp-watch jekyll-serve

[14:46:30] Using gulpfile F:\tabler\gulpfile.js
[14:46:30] Starting 'styles'...
[14:46:30] Starting 'styles-plugins'...
[14:46:31] Finished 'styles-plugins' after 378 ms
[14:46:31] Finished 'styles' after 902 ms
[14:46:31] Starting 'build'...
[14:46:31] Finished 'build' after 80 μs

> tabler-ui@0.0.31 gulp-watch F:\tabler
> gulp watch

> tabler-ui@0.0.31 jekyll-serve F:\tabler
> jekyll serve --livereload

[14:46:33] Using gulpfile F:\tabler\gulpfile.js
[14:46:33] Starting 'styles'...
[14:46:33] Starting 'styles-plugins'...
[14:46:34] Finished 'styles-plugins' after 518 ms
[14:46:34] Finished 'styles' after 1.11 s
[14:46:34] Starting 'watch'...
[14:46:35] Finished 'watch' after 359 ms
Configuration file: F:/tabler/_config.yml
            Source: src
       Destination: F:/tabler/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 3.565 seconds.
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
 Auto-regeneration: enabled for 'src'
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Traceback (most recent call last):
        22: from d:/Ruby25-x64/bin/jekyll:23:in `<main>'
        21: from d:/Ruby25-x64/bin/jekyll:23:in `load'
        20: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/exe/jekyll:15:in `<top (required)>'
        19: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        18: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        17: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        16: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        15: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        14: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        13: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `start'
        12: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `each'
        11: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:93:in `block in start'
        10: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:101:in `process'
         9: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:147:in `register_reload_hooks'
         8: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve.rb:147:in `require_relative'
         7: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve/live_reload_reactor.rb:4:in `<top (required)>'
         6: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/serve/live_reload_reactor.rb:4:in `require'
         5: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/em-websocket-0.5.1/lib/em-websocket.rb:3:in `<top (required)>'
         4: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/em-websocket-0.5.1/lib/em-websocket.rb:3:in `require'
         3: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.5-x64-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
         2: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.5-x64-mingw32/lib/eventmachine.rb:8:in `require'
         1: from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.5-x64-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.5-x64-mingw32/lib/rubyeventmachine.rb:2:in `require': cannot load such file -- 2.5/rubyeventmachine (LoadError)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tabler-ui@0.0.31 jekyll-serve: `jekyll serve --livereload`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tabler-ui@0.0.31 jekyll-serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2018-04-10T06_46_39_226Z-debug.log
ERROR: "jekyll-serve" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tabler-ui@0.0.31 serve: `gulp build && npm-run-all --parallel gulp-watch jekyll-serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tabler-ui@0.0.31 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2018-04-10T06_46_39_474Z-debug.log`

**Comment by DerekTso** [comment]
In case anyone who gets the same issue, please refer to below commands to try to fix it as I did:

- `gem uninstall eventmachine`
- at the prompt tell it to uninstall all versions (it tells you about dependencies)
- `gem install eventmachine --platform ruby`
