### ISSUE TITLE
[BUG] Can not build with laravel MIX

### ISSUE THREAD

**Issue by alighasemzadeh** [tabler/tabler#981]
**Describe the bug**
I am using laravel mix and I use `npm i @tabler/core` I update to Beta5 and now I get this error:
````
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\xampp\htdocs\terra> npm run prod

> prod
> npm run production


> production
> mix --production

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'lru-cache'
Require stack:
- C:\xampp\htdocs\terra\node_modules\semver\classes\range.js
- C:\xampp\htdocs\terra\node_modules\semver\classes\comparator.js
- C:\xampp\htdocs\terra\node_modules\semver\index.js
- C:\xampp\htdocs\terra\node_modules\laravel-mix\src\Engine.js
- C:\xampp\htdocs\terra\node_modules\laravel-mix\bin\cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\xampp\htdocs\terra\node_modules\semver\classes\range.js:187:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\xampp\\htdocs\\terra\\node_modules\\semver\\classes\\range.js',
    'C:\\xampp\\htdocs\\terra\\node_modules\\semver\\classes\\comparator.js',
    'C:\\xampp\\htdocs\\terra\\node_modules\\semver\\index.js',
    'C:\\xampp\\htdocs\\terra\\node_modules\\laravel-mix\\src\\Engine.js',
    'C:\\xampp\\htdocs\\terra\\node_modules\\laravel-mix\\bin\\cli.js'
  ]
}
PS C:\xampp\htdocs\terra> npm install
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

added 786 packages, and audited 787 packages in 60s

87 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\xampp\htdocs\terra> npm run prod

> prod
> npm run production


> production
> mix --production


× Mix
  Compiled with some errors in 17.30s

    

  ERROR in ./resources/sass/app.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[5].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[5].use[4]!./resources/sass/app.scss)
  Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
  SassError: Top-level selectors may not contain the parent selector "&".
     ╷
  17 │   &::-webkit-scrollbar {
     │   ^^^^^^^^^^^^^^^^^^^^^
     ╵
    node_modules\@tabler\core\src\scss\mixins\_mixins.scss 17:3  scrollbar()
    node_modules\@tabler\core\src\scss\layout\_core.scss 33:1    @import
    resources\sass\tabler.scss 4:9                               @import
    resources\sass\app.scss 8:9                                  root stylesheet

  Child mini-css-extract-plugin C:\xampp\htdocs\terra\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[5].use[1]!C:\xampp\htdocs\terra\node_modules\postcss-loader\dist\cjs.js??rul
eSet[1].rules[5].use[2]!C:\xampp\htdocs\terra\node_modules\resolve-url-loader\index.js??ruleSet[1].rules[5].use[3]!C:\xampp\htdocs\terra\node_modules\sass-loader\dist\cjs.js??ruleSet[1].rules[5].use[4]!C:\xampp\htdocs\terra\resources\sass\app.scss compiled with 1 error

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Top-level selectors may not contain the parent selector "&".
   ╷
17 │   &::-webkit-scrollbar {
   │   ^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\@tabler\core\src\scss\mixins\_mixins.scss 17:3  scrollbar()
  node_modules\@tabler\core\src\scss\layout\_core.scss 33:1    @import
  resources\sass\tabler.scss 4:9                               @import
  resources\sass\app.scss 8:9                                  root stylesheet
    at processResult (C:\xampp\htdocs\terra\node_modules\webpack\lib\NormalModule.js:751:19)
    at C:\xampp\htdocs\terra\node_modules\webpack\lib\NormalModule.js:853:5
    at C:\xampp\htdocs\terra\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\xampp\htdocs\terra\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\xampp\htdocs\terra\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at C:\xampp\htdocs\terra\node_modules\sass-loader\dist\index.js:54:7
    at Function.call$2 (C:\xampp\htdocs\terra\node_modules\sass\sass.dart.js:98993:16)
    at render_closure1.call$2 (C:\xampp\htdocs\terra\node_modules\sass\sass.dart.js:84511:12)
    at _RootZone.runBinary$3$3 (C:\xampp\htdocs\terra\node_modules\sass\sass.dart.js:29540:18)
    at _FutureListener.handleError$1 (C:\xampp\htdocs\terra\node_modules\sass\sass.dart.js:28062:21)

webpack compiled with 2 errors
PS C:\xampp\htdocs\terra> npm run prod                   

> prod
> npm run production


> production
> mix --production


× Mix
  Compiled with some errors in 19.82s

    

  ERROR in ./resources/sass/app.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[5].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[5].use[4]!./resources/sass/app.scss)
  Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
  SassError: Top-level selectors may not contain the parent selector "&".
     ╷
  17 │   &::-webkit-scrollbar {
     │   ^^^^^^^^^^^^^^^^^^^^^
     ╵
    node_modules\@tabler\core\src\scss\mixins\_mixins.scss 17:3  scrollbar()
    node_modules\@tabler\core\src\scss\layout\_core.scss 33:1    @import
    resources\sass\tabler.scss 4:9                               @import
    resources\sass\app.scss 8:9                                  root stylesheet

  Child mini-css-extract-plugin C:\xampp\htdocs\terra\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[5].use[1]!C:\xampp\htdocs\terra\node_modules\postcss-loader\dist\cjs.js??rul
eSet[1].rules[5].use[2]!C:\xampp\htdocs\terra\node_modules\resolve-url-loader\index.js??ruleSet[1].rules[5].use[3]!C:\xampp\htdocs\terra\node_modules\sass-loader\dist\cjs.js??ruleSet[1].rules[5].use[4]!C:\xampp\htdocs\terra\resources\sass\app.scss compiled with 1 error

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Top-level selectors may not contain the parent selector "&".
   ╷
17 │   &::-webkit-scrollbar {
   │   ^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\@tabler\core\src\scss\mixins\_mixins.scss 17:3  scrollbar()
  node_modules\@tabler\core\src\scss\layout\_core.scss 33:1    @import
  resources\sass\tabler.scss 4:9                               @import
  resources\sass\app.scss 8:9                                  root stylesheet
    at processResult (C:\xampp\htdocs\terra\node_modules\webpack\lib\NormalModule.js:751:19)
    at C:\xampp\htdocs\terra\node_modules\webpack\lib\NormalModule.js:853:5
    at C:\xampp\htdocs\terra\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\xampp\htdocs\terra\node_modules\loader-runner\lib\LoaderRunner.js:251:18
PS C:\xampp\htdocs\terra> npm run prod

> prod
> npm run production


> production
> mix --production


× Mix
  Compiled with some errors in 9.95s



  ERROR in ./resources/sass/app.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[5].use[3]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[5].use[4]!./resources/sass/app.scss)
  Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
  SassError: Top-level selectors may not contain the parent selector "&".
     ╷
  17 │   &::-webkit-scrollbar {
     │   ^^^^^^^^^^^^^^^^^^^^^
     ╵
    node_modules\@tabler\core\src\scss\mixins\_mixins.scss 17:3  scrollbar()
    node_modules\@tabler\core\src\scss\layout\_core.scss 33:1    @import
    resources\sass\tabler.scss 4:9                               @import
    resources\sass\app.scss 8:9                                  root stylesheet

  Child mini-css-extract-plugin C:\xampp\htdocs\terra\node_modules\css-loader\dist\cjs.js??ruleSet[1].rules[5].use[1]!C:\xampp\htdocs\terra\node_modules\postcss-loader\dist\cjs.js??rul
eSet[1].rules[5].use[2]!C:\xampp\htdocs\terra\node_modules\resolve-url-loader\index.js??ruleSet[1].rules[5].use[3]!C:\xampp\htdocs\terra\node_modules\sass-loader\dist\cjs.js??ruleSet[1].rules[5].use[4]!C:\xampp\htdocs\terra\resources\sass\app.scss compiled with 1 error

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Top-level selectors may not contain the parent selector "&".
   ╷
17 │   &::-webkit-scrollbar {
   │   ^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\@tabler\core\src\scss\mixins\_mixins.scss 17:3  scrollbar()
  node_modules\@tabler\core\src\scss\layout\_core.scss 33:1    @import
  resources\sass\tabler.scss 4:9                               @import
  resources\sass\app.scss 8:9                                  root stylesheet
    at processResult (C:\xampp\htdocs\terra\node_modules\webpack\lib\NormalModule.js:751:19)
    at C:\xampp\htdocs\terra\node_modules\webpack\lib\NormalModule.js:853:5
    at C:\xampp\htdocs\terra\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\xampp\htdocs\terra\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\xampp\htdocs\terra\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at C:\xampp\htdocs\terra\node_modules\sass-loader\dist\index.js:54:7
    at Function.call$2 (C:\xampp\htdocs\terra\node_modules\sass\sass.dart.js:98993:16)
    at render_closure1.call$2 (C:\xampp\htdocs\terra\node_modules\sass\sass.dart.js:84511:12)
    at _RootZone.runBinary$3$3 (C:\xampp\htdocs\terra\node_modules\sass\sass.dart.js:29540:18)
    at _FutureListener.handleError$1 (C:\xampp\htdocs\terra\node_modules\sass\sass.dart.js:28062:21)

webpack compiled with 2 errors
PS C:\xampp\htdocs\terra> 

````

**Comment by FreexD** [comment]
What's your node version? Try downgrading to 14. Same question for the sass compiler?

**Comment by dheineman** [comment]
The webkit-scrollbar related errors should be fixed in main(master) with https://github.com/tabler/tabler/pull/956 however there has not been a new release that includes it.

@codecalm could you tag a beta6 so that that people can use this and the fix from https://github.com/tabler/tabler/pull/963

**Comment by alighasemzadeh** [comment]
@FreexD 
@dheineman 
````
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "npm run production",
        "production": "mix --production"
    },
    "devDependencies": {
        "@popperjs/core": "^2.5.3",
        "alpinejs": "^3.2.6",
        "axios": "^0.21",
        "bootstrap": "^5.1.0",
        "laravel-mix": "^6.0.6",
        "lodash": "^4.17.19",
        "resolve-url-loader": "^4.0.0",
        "sass": "^1.43.4",
        "sass-loader": "^12.1.0"
    },
    "dependencies": {
        "@alpinejs/persist": "^3.6.1",
        "@ryangjchandler/alpine-clipboard": "^2.1.0",
        "@sweetalert2/themes": "^5.0.8",
        "@tabler/core": "^1.0.0-beta4",
        "chart.js": "^3.6.0",
        "cryptocurrency-icons": "^0.18.0",
        "pikaday": "^1.8.2",
        "sweetalert2": "^11.2.1",
        "vazir-font": "^30.1.0"
    }
}
````

Node Version:v16.13.1

**Comment by FreexD** [comment]
Ok, that's probably a `sass` package related issue... @alighasemzadeh you should probably wait for #956 to get merged and beta-6 released. All works fine for me in node v16.13.1 but I'm using `node-sass` instead ;)

**Comment by alighasemzadeh** [comment]
@FreexD 
Did you use Webpcak?

**Comment by FreexD** [comment]
Yes

**Comment by alighasemzadeh** [comment]
Can you share your webpack config?
@FreexD

**Comment by shukriYusof** [comment]
@alighasemzadeh have you found a solution yet ?

**Comment by alighasemzadeh** [comment]
@shukriYusof 
You can use:
[alighasemzadeh/bap
](https://github.com/alighasemzadeh/bap)

**Comment by alighasemzadeh** [comment]
Fixed in beta6.
